#howto: http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION -batch -v clean test

notifications:
  email: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
